### ISSUE TITLE
6.0beta #21848 - Canceling drag from messageNames pane opens a new window

### ISSUE THREAD

**Issue by tcj** [squeak-smalltalk/squeak-object-memory#34] opened 2022-06-05 21:30 UTC
Dragging a messageName (method list item) from the right-most pane of a browser is a feature that has existed for some time.  It used to be that one could "cancel" the drag by returning the drag to its original source pane and releasing the mouse button.  This would 'repel' the dragged morph and make the 'garbage can' sound, one of those cute Morphic animations.

![Screen Shot 2022-06-05 at 2 28 17 PM](https://user-images.githubusercontent.com/2293335/172071411-ff950525-5218-4711-9075-b557e4056404.png)

But now, in 6.0beta-21848 (and earlier?), letting go of the drag with the pointer *over the original position* instead opens up a new window with a message list browser.

![Screen Shot 2022-06-05 at 2 29 49 PM](https://user-images.githubusercontent.com/2293335/172071447-837bc52f-326e-4b14-8014-a3278f688be6.png)

Screen recording here:

https://youtu.be/DW68lMEc49c

Can the previous behavior of canceling the drag and repelling the morph be resurrected?  No window should open in this case.

**Comment by marceltaeumel** [comment] 2022-06-09 07:05
This is not a bug. If you want to cancel a drag operation, you have to press the "Escape" key.

This is the first time I heard that a user wants to cancel a drag operation by carefully moving it back to its original source. This sounds very cumbersome and not what you want by default.

What is happening here is that, originally, the drop, which landed on the world (or background) ... not the browser ... would be repelled because the world did not know what to do with it.

We changed this to a meaningful guesture so that you can collect selected code artifacts on your screen.

---

Cancel a drag operation with the "Escape" key. That's the default gesture in most systems out there.

**Closed** 2022-06-09 07:07 UTC
Labels: ignored, user, ui system

**Comment by marceltaeumel** [comment] 2022-06-10 08:21
> With the new behavior [...]

Well, that "drag back to original source" was never implemented. It was just an unintentional side effect of the world morph repelling all such drop operations...

> This new functionality gets-in-the-way-of the "stop, I don't want to do this anymore" portion of that gesture.

Let's not mix up things. That new gesture only applies of the tool itself does not want that drop operation. So, I think you just found a bug with that method-drag-drop interaction between browsers.

> I believe there are keyboard shortcuts and menu items to open browsers on selected message names already without impact existing behavior.

Such keyboard shortcuts are hard to learn. Keyboard-based and mouse-based navigation are two different concepts that are often not exclusive but rather redundant.

**Comment by marceltaeumel** [comment] 2022-06-10 08:28
> Dragging a message name from this pane to another browser (to move it to a different class) or another message category (to recategorize) is a gesture that already existed in Squeak.

When was that? I just checked Squeak 4.4. Dragging methods betwen classes is not supported.

**Comment by marceltaeumel** [comment] 2022-06-10 08:30
> [...] menu items to open browsers on selected message names [...]

It is not convenient to collect methods via the regular System Browser. Too much visual clutter. Just using a CodeHolder is much more compact.

**Comment by tcj** [comment] 2022-06-10 15:17
> When was that? I just checked Squeak 4.4. Dragging methods betwen classes is not supported.

Not true.  I can do it.  Here's a video.

https://youtu.be/MaVPlWQ9sjc

And a screenshot:

![Screen Shot 2022-06-10 at 8 15 37 AM](https://user-images.githubusercontent.com/2293335/173096989-37d28cdb-ce1c-476d-a3bf-ef288b918a40.png)

Note that dragging while holding Shift changes the visuals to have a red "+" sign indicating the method will be copied.

![Screen Shot 2022-06-10 at 8 15 09 AM](https://user-images.githubusercontent.com/2293335/173097174-eeee6e63-e3f7-4e99-8c9c-8264e9d53eaa.png)

**Comment by tcj** [comment] 2022-06-10 15:19
> > [...] menu items to open browsers on selected message names [...]
> 
> It is not convenient to collect methods via the regular System Browser. Too much visual clutter. Just using a CodeHolder is much more compact.

My point is that one can already quickly open new browsers on message names using existing menus, without resorting to dragging.  Here is a video.

https://youtu.be/2K1FPX3fjA8

**Comment by tcj** [comment] 2022-06-10 15:40
> Such keyboard shortcuts are hard to learn. Keyboard-based and mouse-based navigation are two different concepts that are often not exclusive but rather redundant.

I'm just thinking of this statement in context of "press Escape on your keyboard to cancel your mouse drag operation."  I realize it does not relate 1:1, but philosophically there is some resemblance.
