### ISSUE TITLE
MessageSet MNU: RemoteString>>methodClass

### ISSUE THREAD

**Issue by nicolas-cellier-aka-nice** [squeak-smalltalk/squeak-object-memory#93] opened 2023-08-21 16:26 UTC
**How to reproduce?**

    "1) Open a MessageNames searching for fft"
    window := StandardToolSet browseMessageNames: 'fft'.

    "2) Select the FFT selector (class name actually) in the left pane"
    window model selectorListIndex: 1.

    "3) Select the 'FFT comment' in the right pane"
    window model messageListIndex: 2.

    "4) Select the fftAt: selector in the left pane"
    window model selectorListIndex: 2.

**What happens?**

During step 3, the `MessageSet>>selectedMessage` sets the `currentCompiledMethod` inst. var. of the MessageSet to a `RemoteString` (pointing to the comment of FFT class).

During step 4, `MessageNames>>selectorListIndex:` tries to retrieve the class implementing selected message (or nil).<br>
It expects `currentCompiledMethod` to be either a `CompiledMethod` or `nil`, not a `RemoteString`.

**How to Solve?**

Avoiding to set `currentCompiledMethod := class organization commentRemoteStr.` in `MessageSet>>selectedMessage` solves the problem...

However, since such patch is in a superclass, it might break another subclass expecting to find a RemoteString in `currentCompiledMethod` inst. var., who knows?

**Comment by nicolas-cellier-aka-nice** [comment] 2023-08-21 16:56
I found only one method expecting `currentCompiledMethod` to be a `RemoteString`:

that is in `CodeHolder>>didCodeChangeElsewhere`

	self classCommentIndicated
		ifTrue: [^ currentCompiledMethod ~~ aClass organization commentRemoteStr].

So we would have to store the RemoteString into another inst. var. in order to perform such check...

**Comment by marceltaeumel** [comment] 2023-08-22 07:47
I think this is a regression from "eem 12/6/2015 12:19" following  "mt 5/8/2015 11:25". Let me look into why the change was made.

**Comment by marceltaeumel** [comment] 2023-08-22 08:07
Fixed via Tools-mt.1230. Note that this bug cannot show in Squeak 6.0 because there, users cannot browse comment, definition, or hierarchy of classes in the `MessageNames` tool.

**Closed by marceltaeumel** 2023-08-22 08:07 UTC
Labels: tools and libraries, bug
